[book]
authors = ["Huilin-Li"]
language = "en"
src = "src"
title = "Huilin's Book"


[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "navy"
smart-punctuation = true
mathjax-support = true
no-section-label = false
git-repository-url = "https://github.com/Huilin-Li/myNotebook"
git-repository-icon = "fa-github"
site-url = "/example-book/"

[output.html.fold]
enable = false    # whether or not to enable section folding
level = 0         # the depth to start folding

[output.html.redirect]
"/appendices/bibliography.html" = "https://rustc-dev-guide.rust-lang.org/appendix/bibliography.html"

